### ISSUE TITLE
ValueError: Points outside of mesh when switching from OcTree to Tensor Mesh

### ISSUE THREAD

**Issue by Furlan63** [simpeg/simpeg#1081]
I have a 3D tipper inversion that uses "mesh_builder_xyz()" and my receiver locations to construct an OcTree mesh. I wanted to test the inversion using a tensor mesh but it's telling me the points are outside the mesh? The input files are the same. Below is how I've built them.

**Tensor:**
mesh = mesh_builder_xyz(receiver_locations, cell_array, padding_distance=pad_array, expansion_factor=1.3, mesh_type='tensor')

**Tree:**
mesh = mesh_builder_xyz(receiver_locations, cell_array, padding_distance=pad_array, mesh_type='tree')

**The error I'm getting:**
Traceback (most recent call last):

  File "C:\User\3D_Inv\INV.py", line 573, in <module>
    minv = inv.run(m_bg)

  File "C:\SimPEG\lib\site-packages\SimPEG\utils\counter_utils.py", line 105, in wrapper
    out = f(self, *args, **kwargs)

  File "C:\SimPEG\lib\site-packages\SimPEG\inversion.py", line 64, in run
    self.directiveList.call("initialize")

  File "C:\SimPEG\lib\site-packages\SimPEG\directives\directives.py", line 199, in call
    getattr(r, ruleType)()

  File "C:\SimPEG\lib\site-packages\SimPEG\directives\directives.py", line 2052, in initialize
    self.update()

  File "C:\SimPEG\lib\site-packages\SimPEG\directives\directives.py", line 2063, in update
    self.getJtJdiag()

  File "C:\SimPEG\lib\site-packages\SimPEG\directives\directives.py", line 2087, in getJtJdiag
    self.JtJdiag += [dmisfit.getJtJdiag(m) / cell_volumes**2.]

  File "C:\SimPEG\lib\site-packages\SimPEG\data_misfit.py", line 192, in getJtJdiag
    jtjdiag = self.simulation.getJtJdiag(m, W=self.W)

  File "C:\SimPEG\lib\site-packages\SimPEG\dask\electromagnetics\frequency_domain\simulation.py", line 51, in dask_getJtJdiag
    if isinstance(self.Jmatrix, Future):

  File "C:\SimPEG\lib\site-packages\SimPEG\dask\simulation.py", line 146, in Jmatrix
    self._Jmatrix = self.compute_J()

  File "C:\SimPEG\lib\site-packages\SimPEG\dask\electromagnetics\frequency_domain\simulation.py", line 147, in compute_J
    dfduT, dfdmT = rx.evalDeriv(

  File "C:\SimPEG\lib\site-packages\SimPEG\electromagnetics\natural_source\receivers.py", line 822, in evalDeriv
    imp_deriv = self._eval_tipper_deriv(

  File "C:\SimPEG\lib\site-packages\SimPEG\electromagnetics\natural_source\receivers.py", line 732, in _eval_tipper_deriv
    Phx = self.getP(mesh, "Fx", "h")

  File "C:\SimPEG\lib\site-packages\SimPEG\electromagnetics\natural_source\receivers.py", line 115, in getP
    P = mesh.getInterpolationMat(locs, projGLoc)

  File "C:\SimPEG\lib\site-packages\discretize\utils\code_utils.py", line 222, in new_method
    return getattr(self, new_name)(*args, **kwargs)

  File "C:\SimPEG\lib\site-packages\discretize\base\base_tensor_mesh.py", line 1045, in get_interpolation_matrix
    return self._getInterpolationMat(loc, location_type, zeros_outside)

  File "C:\SimPEG\lib\site-packages\discretize\base\base_tensor_mesh.py", line 879, in _getInterpolationMat
    raise ValueError("Points outside of mesh")

ValueError: Points outside of mesh

**Comment by domfournier** [comment]
Can you check what the `mesh.origin` returns? 
This sounds familiar, and it could be a bug with the `discretize.utils.mesh_utils.mesh_builder_xyz` origin setter.

**Comment by Furlan63** [comment]
The first origin and node_x value are the same in both cases. I also checked node_y[0] vs origin[1] & node_z[0] with origin[2] and they match as well.

mesh.origin[0]
Out[16]: 587817.0

mesh.nodes_x[0]
Out[17]: 587817.0

meshTENSOR.nodes_x[0]
Out[18]: 589915.500209

meshTENSOR.origin[0]
Out[19]: 589915.500209

**Comment by Furlan63** [comment]
My Z max for the tensor mesh didn't reach the highest Z value in my receiver locations.

Here is the Tensor Info:

    TensorMesh: 31,980 cells

                      MESH EXTENT             CELL WIDTH      FACTOR
    dir    nC        min           max         min       max      max
    ---   ---  ---------------------------  ------------------  ------
     x     41    589,915.50    598,618.50    100.00    815.73    1.30
     y     39  7,144,298.50  7,152,801.50    100.00    815.73    1.30
     z     20     -2,920.75      1,195.60     50.00    896.08    1.30
    
Here is the max Z value for my receivers:

    In [36]: max(receiver_locations[:,2])
    Out[36]: 1207.02

1195.60 < 1207.02

The OcTree mesh, however, does include these values.

    Level : Number of cells               Mesh Extent               Cell Widths    
    -----------------------           min     ,     max            min   ,   max   
      2   :       24             ---------------------------   --------------------
      3   :       250         x:   587817.0   ,  600617.0        100.0   ,   3200.0  
      4   :       382         y:   7142100.0  ,  7154900.0       100.0   ,   3200.0  
      5   :       850         z:    -2254.4   ,   4145.6          50.0   , 1600.0
      6   :      2105      
      7   :      19896     
    -----------------------
    Total :      23507     >

4145.6 > 1207.02

Originally, I added padding in every direction except for up:

    pad_array = [[skn_d*2, skn_d*2],
                 [skn_d*2, skn_d*2],
                 [skn_d*2, 0]]

So I changed this to:

    pad_array = [[skn_d*2, skn_d*2],
                 [skn_d*2, skn_d*2],
                 [skn_d*2, 100]]

And the code ran, albeit demanding a lot more memory.

**Comment by domfournier** [comment]
Ok yep, makes sense. By default, the octree mesh gets centered on the data. Plus the padding gets rounded up to the next power of 2, so you will always be inside... 

I guess the issue is resolved?

**Comment by Furlan63** [comment]
Yes I will close the issue now.
