### ISSUE TITLE
BUG: Some tutorials are failing when trying to build the docs

### ISSUE THREAD

**Issue by santisoler** [simpeg/simpeg#1379]
### Describe the issue:

While working on #1378 I tried to build the docs locally to see the latest changes. But I noticed that some of the tutorials run into errors when Sphinx is trying to render them.

The tutorials that are failing are:
- `tutorials/05-dcr/plot_inv_2_dcr2d.py`
- `tutorials/06-ip/plot_inv_2_dcip2d.py`
- `tutorials/05-dcr/plot_inv_2_dcr2d_irls.py`
- `tutorials/06-ip/plot_fwd_2_dcip2d.py`
- `tutorials/05-dcr/plot_fwd_2_dcr2d.py`

All fail because of the same reason.

### Reproducible code example:

```bash
python tutorials/05-dcr/plot_fwd_2_dcr2d.py
```

### Error message:

```
/home/santi/git/simpeg/tutorials/05-dcr/plot_fwd_2_dcr2d.py:126: DeprecationWarning: The surface option is deprecated as of `0.9.0` please update your code to use the `TreeMesh.refine_surface` functionality. It will be removed in a future version of discretize.
  mesh = refine_tree_xyz(
/home/santi/.mambaforge/envs/simpeg-test/lib/python3.11/site-packages/scipy/interpolate/_interpolate.py:710: RuntimeWarning: invalid value encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
Traceback (most recent call last):
  File "/home/santi/git/simpeg/tutorials/05-dcr/plot_fwd_2_dcr2d.py", line 126, in <module>
    mesh = refine_tree_xyz(
           ^^^^^^^^^^^^^^^^
  File "/home/santi/.mambaforge/envs/simpeg-test/lib/python3.11/site-packages/discretize/utils/mesh_utils.py", line 837, in refine_tree_xyz
    r, ind = tree.query(newLoc)
             ^^^^^^^^^^^^^^^^^^
  File "_ckdtree.pyx", line 795, in scipy.spatial._ckdtree.cKDTree.query
ValueError: 'x' must be finite, check for nan or inf values
```

### Runtime information:

```
--------------------------------------------------------------------------------
  Date: Tue Mar 12 16:24:44 2024 PDT

                OS : Linux
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.6 GiB
       Environment : IPython
       File system : ext4

  Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC
  12.3.0]

            SimPEG : 0.20.0.post3.dev86+geb15c444f
        discretize : 0.10.0
       pymatsolver : 0.2.0
             numpy : 1.26.4
             scipy : 1.12.0
           sklearn : 1.4.1.post1
        matplotlib : 3.8.3
           empymod : 2.3.0
            geoana : 0.6.0
            pandas : 2.2.1
            pydiso : 0.0.3
             numba : 0.59.0
              dask : 2024.2.1
             sympy : 1.12
           IPython : 8.22.2
        ipywidgets : 8.1.2
            plotly : 5.19.0
               vtk : 9.2.6
   memory_profiler : 0.61.0
            choclo : 0.1.0
--------------------------------------------------------------------------------
```

**Comment by jcapriot** [comment]
This should be fixed by updating the call from the deprecated `refine_tree_xyz` function, as the new one doesn't use a KDtree.

**Comment by santisoler** [comment]
Great! I'll fix that and check if they build locally. Thanks for pointing it out @jcapriot!
