### ISSUE TITLE
BUG: `GaussianMixtureWithPrior.fit_predict` fails with latest version of scikit-learn

### ISSUE THREAD

**Issue by santisoler** [simpeg/simpeg#1475]
### Describe the issue:

Running the `tutorials/14-pgi/plot_inv_2_joint_pf_pgi_no_info_tutorial.py` with the `scikit-learn==1.5.0` falls into an error due to a change in a private method from the upstream `BaseMixture` class.

### Reproducible code example:

```python
python tutorials/14-pgi/plot_inv_2_joint_pf_pgi_no_info_tutorial.py
```

### Error message:

```shell
Downloading https://storage.googleapis.com/simpeg/pgi_tutorial_assets/mesh_tutorial.ubc
   saved to: /home/santi/git/simpeg/mesh_tutorial.ubc
Download completed!
Downloading https://storage.googleapis.com/simpeg/pgi_tutorial_assets/geology_true.mod
   saved to: /home/santi/git/simpeg/geology_true.mod
Download completed!
Downloading https://storage.googleapis.com/simpeg/pgi_tutorial_assets/gravity_data.obs
   saved to: /home/santi/git/simpeg/gravity_data.obs
Download completed!
Downloading https://storage.googleapis.com/simpeg/pgi_tutorial_assets/magnetic_data.obs
   saved to: /home/santi/git/simpeg/magnetic_data.obs
Download completed!
Downloading https://storage.googleapis.com/simpeg/pgi_tutorial_assets/CDED_Lake_warp.xyz
   saved to: /home/santi/git/simpeg/CDED_Lake_warp.xyz
Download completed!

                    simpeg.InvProblem is setting bfgsH0 to the inverse of the eval2Deriv.
                    ***Done using the default solver Pardiso and no solver_opts.***

Alpha scales: [9476216.801984344, 0.0, 6214450.074856385, 0.0, 13503557.75164027, 0.0, 981099553.7221122, 0.0, 736291450.040535, 0.0, 1846725954.305293, 0.0]
<class 'simpeg.regularization.pgi.PGIsmallness'>
Initial data misfit scales:  [0.98049879 0.01950121]
model has any nan: 0
=============================== Projected GNCG ===============================
  #     beta     phi_d     phi_m       f      |proj(x-g)-x|  LS    Comment
-----------------------------------------------------------------------------
x0 has any nan: 0
   0  1.42e-08  4.27e+06  9.99e+04  4.27e+06    2.17e+02      0
Traceback (most recent call last):
  File "/home/santi/git/simpeg/tutorials/14-pgi/plot_inv_2_joint_pf_pgi_no_info_tutorial.py", line 448, in <module>
    pgi_model_no_info = inv.run(m0)
                        ^^^^^^^^^^^
  File "/home/santi/git/simpeg/simpeg/utils/counter_utils.py", line 136, in wrapper
    out = f(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/git/simpeg/simpeg/inversion.py", line 113, in run
    self.m = self.opt.minimize(self.invProb.evalFunction, self.invProb.model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/git/simpeg/simpeg/utils/counter_utils.py", line 136, in wrapper
    out = f(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/git/simpeg/simpeg/optimization.py", line 396, in minimize
    self.doEndIteration(xt)
  File "/home/santi/git/simpeg/simpeg/utils/counter_utils.py", line 116, in wrapper
    out = f(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/git/simpeg/simpeg/utils/code_utils.py", line 357, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/git/simpeg/simpeg/optimization.py", line 692, in doEndIteration
    self.callback(xt)
  File "/home/santi/git/simpeg/simpeg/inversion.py", line 119, in _optCallback
    self.directiveList.call("endIter")
  File "/home/santi/git/simpeg/simpeg/directives/directives.py", line 334, in call
    getattr(r, ruleType)()
  File "/home/santi/git/simpeg/simpeg/directives/pgi_directives.py", line 116, in endIter
    clfupdate = clfupdate.fit(model)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/santi/git/simpeg/simpeg/utils/pgi_utils.py", line 1082, in fit
    self.fit_predict(X, y, debug)
  File "/home/santi/git/simpeg/simpeg/utils/pgi_utils.py", line 1173, in fit_predict
    self._print_verbose_msg_init_end(lower_bound)
TypeError: BaseMixture._print_verbose_msg_init_end() missing 1 required positional argument: 'init_has_converged'
```

### Runtime information:

 ```
  Date: Wed Jun 05 08:51:27 2024 PDT

                OS : Linux (Debian GNU/Linux 12)
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GiB
       Environment : Python
       File system : ext4

  Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC
  12.3.0]

            simpeg : 0.21.2.dev27+gcbd200b67
        discretize : 0.10.0
       pymatsolver : 0.2.0
             numpy : 1.26.4
             scipy : 1.13.1
           sklearn : 1.5.0
        matplotlib : 3.8.4
           empymod : 2.3.0
            geoana : 0.6.0
            pandas : 2.2.2
            pydiso : 0.0.5
             numba : 0.59.1
              dask : 2024.5.2
             sympy : 1.12
           IPython : 8.25.0
        ipywidgets : 8.1.3
            plotly : 5.22.0
               vtk : 9.2.6
   memory_profiler : 0.61.0
            choclo : 0.2.0
```

**Comment by santisoler** [comment]
I think we can solve this by updating the call to the private method. Although for the long term support of the gaussian mixture classes we could explore refactoring the code to avoid using these private methods that are not guaranteed to not change between minor releases of scikit-learn.

**Comment by jcapriot** [comment]
> I think we can solve this by updating the call to the private method. Although for the long term support of the gaussian mixture classes we could explore refactoring the code to avoid using these private methods that are not guaranteed to not change between minor releases of scikit-learn.

I didn’t get a chance to get to the meeting today, but I would say we should put in a PR onto sci-kit learn to enable their Gaussian mixture to accept sample weights. That should simplify a lot of what we have to do here.

**Comment by santisoler** [comment]
Agree. A lot of scikit-learn classes allow to pass `sample_weights` to their `fit` methods. The mixture classes don't. It would be great if we had that support upstream so we can simplify the code for our own GMMs.
