### ISSUE TITLE
How to Implementing Anisotrophy for Conductivity in  a new version of Simpeg

### ISSUE THREAD

**Issue by wsheat** [simpeg/simpeg#1488]
### Describe the issue:

I've noticed the example for Anisotrophy of Conductivity  in  github(https://github.com/simpeg-research/heagy-2018-fracture-physprops/tree/master). But the version of Simpeg  were using at the time was 0.10.4.
I'm trying to implement anisotropy of conductivity in 0.20.0, but the code doesn't run when I input conductivity (n_c,3) into the simulation class. I would appreciate a simple demonstration for this

### Reproducible code example:

```python
simulation = tdem.simulation.Simulation3DElectricField( mesh, survey=survey, sigmaMap=model_map,sigma=sigma_aniso, solver=Solver, t0=0)
simulation.time_steps = time_steps
sigma_aniso = sigma_back * np.ones((ind_active.sum(), 3))
dpred = simulation.dpred(sigma_aniso)
```

### Runtime information:

--------------------------------------------------------------------------------Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/home/cdut5815/.conda/envs/Simpeg/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cdut5815/.conda/envs/Simpeg/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cdut5815/.vscode/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/cdut5815/.vscode/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/cdut5815/.vscode/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/cdut5815/.vscode/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/cdut5815/.vscode/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/cdut5815/.vscode/extensions/ms-python.python-2024.4.1/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/cdut5815/download/Simpeg/tem_code/tem_facture.py", line 241, in <module>
    dpred = simulation.dpred(sigma_aniso)
  File "/home/cdut5815/.conda/envs/Simpeg/lib/python3.9/site-packages/SimPEG/simulation.py", line 448, in dpred
    f = self.fields(m)
  File "/home/cdut5815/.conda/envs/Simpeg/lib/python3.9/site-packages/SimPEG/electromagnetics/time_domain/simulation.py", line 88, in fields
    self.model = m
  File "/home/cdut5815/.conda/envs/Simpeg/lib/python3.9/site-packages/SimPEG/base/pde_simulation.py", line 518, in __setattr__
    super().__setattr__(name, value)
  File "/home/cdut5815/.conda/envs/Simpeg/lib/python3.9/site-packages/SimPEG/base/pde_simulation.py", line 542, in __setattr__
    super().__setattr__(name, value)
  File "/home/cdut5815/.conda/envs/Simpeg/lib/python3.9/site-packages/SimPEG/props.py", line 403, in model
    value = validate_ndarray_with_shape(
  File "/home/cdut5815/.conda/envs/Simpeg/lib/python3.9/site-packages/SimPEG/utils/code_utils.py", line 1071, in validate_ndarray_with_shape
    raise ValueError(
ValueError: The dimensions of the input argument 'var' are greater than is specified by 'shape'

**Comment by santisoler** [comment]
cc @lheagy
