### ISSUE TITLE
BUG: Error while running mag inversion 

### ISSUE THREAD

**Issue by Alexzqyyds** [simpeg/simpeg#1539]
### Describe the issue:

Dear Developer,

I encountered an issue while performing magnetic inversion, and the system notified me with the following message: "gstrf was called with invalid arguments." My dataset contains approximately 400,000 entries, and I am working on a machine with 32 GB of RAM. Could you please advise on how I might resolve this issue?

Thank you for your assistance.

### Reproducible code example:

```python
# Import modules
# --------------
import os
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
from discretize import TensorMesh
from discretize.utils import active_from_xyz
from simpeg.potential_fields import magnetics
from simpeg.utils import plot2Ddata, model_builder
from simpeg import (
    maps,
    data,
    inverse_problem,
    data_misfit,
    regularization,
    optimization,
    directives,
    inversion,
)

# 替换文件路径并确保使用原始字符串来避免转义问题
topo_filename = r"D:\GitHub\simpeg-main\tutorials\04-magnetics\MRInv_surf.txt"
data_filename = r"D:\GitHub\simpeg-main\tutorials\04-magnetics\MRInv_mag.txt"

# 加载数据并检查是否正确加载
try:
    topo_xyz = pd.read_csv(topo_filename, sep=r'\s+', header=None, encoding='utf-16').values
    dobs = pd.read_csv(data_filename, sep=r'\s+', header=None, encoding='utf-16').values
except Exception as e:
    print(f"Error loading data: {e}")
    raise

# 验证数据形状是否正确
if topo_xyz.size == 0 or dobs.size == 0:
    raise ValueError("Loaded data is empty, please check the input files.")

receiver_locations = dobs[:, 0:3]
dobs = dobs[:, -1]

# 绘制数据
fig = plt.figure(figsize=(6, 5))
v_max = np.max(np.abs(dobs))

ax1 = fig.add_axes([0.1, 0.1, 0.75, 0.85])
plot2Ddata(
    receiver_locations,
    dobs,
    ax=ax1,
    ncontour=30,
    clim=(-v_max, v_max),
    contourOpts={"cmap": "bwr"},
)
ax1.set_title("TMI Anomaly")
ax1.set_xlabel("x (m)")
ax1.set_ylabel("y (m)")

ax2 = fig.add_axes([0.85, 0.05, 0.05, 0.9])
norm = mpl.colors.Normalize(vmin=-np.max(np.abs(dobs)), vmax=np.max(np.abs(dobs)))
cbar = mpl.colorbar.ColorbarBase(
    ax2, norm=norm, orientation="vertical", cmap=mpl.cm.bwr
)
cbar.set_label("$nT$", rotation=270, labelpad=15, size=12)

plt.show()
maximum_anomaly = np.max(np.abs(dobs))

std = 0.02 * maximum_anomaly * np.ones(len(dobs))
components = ["tmi"]
receiver_list = magnetics.receivers.Point(receiver_locations, components=components)

receiver_list = [receiver_list]
inclination = 90
declination = 0
strength = 50000

source_field = magnetics.sources.UniformBackgroundField(
    receiver_list=receiver_list,
    amplitude=strength,
    inclination=inclination,
    declination=declination,
)
survey = magnetics.survey.Survey(source_field)
data_object = data.Data(survey, dobs=dobs, standard_deviation=std)
dh = 10000.0
hx = [(dh, 10, -1.3), (dh, 100), (dh, 10, 1.3)]
hy = [(dh, 10, -1.3), (dh, 100), (dh, 10, 1.3)]
hz = [(dh, 10, -1.3), (dh, 50)]
mesh = TensorMesh([hx, hy, hz], "CCN")
background_susceptibility = 1e-4
active_cells = active_from_xyz(mesh, topo_xyz)
nC = int(active_cells.sum())
model_map = maps.IdentityMap(nP=nC) 
starting_model = background_susceptibility * np.ones(nC)
simulation = magnetics.simulation.Simulation3DIntegral(
    survey=survey,
    mesh=mesh,
    model_type="scalar",
    chiMap=model_map,
    ind_active=active_cells,
    engine="choclo",
)
dmis = data_misfit.L2DataMisfit(data=data_object, simulation=simulation)
reg = regularization.Sparse(
    mesh,
    active_cells=active_cells,
    mapping=model_map,
    reference_model=starting_model,
    gradient_type="total",
)
reg.norms = [0, 0, 0, 0]
opt = optimization.ProjectedGNCG(
    maxIter=20, lower=0.0, upper=1.0, maxIterLS=20, maxIterCG=10, tolCG=1e-3
)
inv_prob = inverse_problem.BaseInvProblem(dmis, reg, opt)
starting_beta = directives.BetaEstimate_ByEig(beta0_ratio=5)
save_iteration = directives.SaveOutputEveryIteration(save_txt=False)
update_IRLS = directives.Update_IRLS(
    f_min_change=1e-4,
    max_irls_iterations=30,
    coolEpsFact=1.5,
    beta_tol=1e-2,
)
update_jacobi = directives.UpdatePreconditioner()
target_misfit = directives.TargetMisfit(chifact=1)
directives_list = [
    sensitivity_weights,
    starting_beta,
    save_iteration,
    update_IRLS,
    update_jacobi,
]
inv = inversion.BaseInversion(inv_prob, directives_list)
recovered_model = inv.run(starting_model)
background_susceptibility = 0.0001
sphere_susceptibility = 0.01

true_model = background_susceptibility * np.ones(nC)
ind_sphere = model_builder.get_indices_sphere(
    np.r_[0.0, 0.0, -45.0], 15.0, mesh.cell_centers
)
ind_sphere = ind_sphere[active_cells]
true_model[ind_sphere] = sphere_susceptibility
fig = plt.figure(figsize=(9, 4))
plotting_map = maps.InjectActiveCells(mesh, active_cells, np.nan)

ax1 = fig.add_axes([0.08, 0.1, 0.75, 0.8])
mesh.plot_slice(
    plotting_map * true_model,
    normal="Y",
    ax=ax1,
    ind=int(mesh.shape_cells[1] / 2),
    grid=True,
    clim=(np.min(true_model), np.max(true_model)),
    pcolor_opts={"cmap": "viridis"},
)
ax1.set_title("Model slice at y = 0 m")

ax2 = fig.add_axes([0.85, 0.1, 0.05, 0.8])
norm = mpl.colors.Normalize(vmin=np.min(true_model), vmax=np.max(true_model))
cbar = mpl.colorbar.ColorbarBase(
    ax2, norm=norm, orientation="vertical", cmap=mpl.cm.viridis, format="%.1e"
)
cbar.set_label("SI", rotation=270, labelpad=15, size=12)

plt.show()
fig = plt.figure(figsize=(9, 4))
plotting_map = maps.InjectActiveCells(mesh, active_cells, np.nan)

ax1 = fig.add_axes([0.08, 0.1, 0.75, 0.8])
mesh.plot_slice(
    plotting_map * recovered_model,
    normal="Y",
    ax=ax1,
    ind=int(mesh.shape_cells[1] / 2),
    grid=True,
    clim=(np.min(recovered_model), np.max(recovered_model)),
    pcolor_opts={"cmap": "viridis"},
)
ax1.set_title("Model slice at y = 0 m")

ax2 = fig.add_axes([0.85, 0.1, 0.05, 0.8])
norm = mpl.colors.Normalize(vmin=np.min(recovered_model), vmax=np.max(recovered_model))
cbar = mpl.colorbar.ColorbarBase(
    ax2, norm=norm, orientation="vertical", cmap=mpl.cm.viridis, format="%.1e"
)
cbar.set_label("SI", rotation=270, labelpad=15, size=12)

plt.show()
dpred = inv_prob.dpred
data_array = np.c_[dobs, dpred, (dobs - dpred) / std]

fig = plt.figure(figsize=(17, 4))
plot_title = ["Observed", "Predicted", "Normalized Misfit"]
plot_units = ["nT", "nT", ""]

ax1 = 3 * [None]
ax2 = 3 * [None]
norm = 3 * [None]
cbar = 3 * [None]
cplot = 3 * [None]
v_lim = [np.max(np.abs(dobs)), np.max(np.abs(dobs)), np.max(np.abs(data_array[:, 2]))]

for ii in range(0, 3):
    ax1[ii] = fig.add_axes([0.33 * ii + 0.03, 0.11, 0.25, 0.84])
    cplot[ii] = plot2Ddata(
        receiver_list[0].locations,
        data_array[:, ii],
        ax=ax1[ii],
        ncontour=30,
        clim=(-v_lim[ii], v_lim[ii]),
        contourOpts={"cmap": "bwr"},
    )
    ax1[ii].set_title(plot_title[ii])
    ax1[ii].set_xlabel("x (m)")
    ax1[ii].set_ylabel("y (m)")

    ax2[ii] = fig.add_axes([0.33 * ii + 0.27, 0.11, 0.01, 0.84])
    norm[ii] = mpl.colors.Normalize(vmin=-v_lim[ii], vmax=v_lim[ii])
    cbar[ii] = mpl.colorbar.ColorbarBase(
        ax2[ii], norm=norm[ii], orientation="vertical", cmap=mpl.cm.bwr
    )
    cbar[ii].set_label(plot_units[ii], rotation=270, labelpad=15, size=12)

plt.show()
```

### Runtime information:

Mesh shape (cells): (120, 120, 60)

Running inversion with SimPEG v0.22.2

                    simpeg.InvProblem is setting bfgsH0 to the inverse of the eval2Deriv.
                    ***Done using the default solver SolverLU and no solver_opts.***

Can't expand MemType 0: jcol 798940
Traceback (most recent call last):
  File "d:\GitHub\simpeg-main\tutorials\04-magnetics\inversion_test1.py", line 321, in <module>
    recovered_model = inv.run(starting_model)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\envs\newenv\Lib\site-packages\simpeg\utils\counter_utils.py", line 136, in wrapper
    out = f(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\envs\newenv\Lib\site-packages\simpeg\inversion.py", line 110, in run
    self.invProb.startup(m0)
  File "E:\Anaconda\envs\newenv\Lib\site-packages\simpeg\utils\code_utils.py", line 364, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\envs\newenv\Lib\site-packages\simpeg\inverse_problem.py", line 236, in startup
    self.opt.bfgsH0 = solver(
                      ^^^^^^^
  File "E:\Anaconda\envs\newenv\Lib\site-packages\simpeg\utils\solver_utils.py", line 98, in __init__
    self.solver = fun(self.A, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\envs\newenv\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py", line 438, in splu
    return _superlu.gstrf(N, A.nnz, A.data, indices, indptr,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: gstrf was called with invalid arguments

**Comment by santisoler** [comment]
Hi @Alexzqyyds. Thanks for opening this issue.

A couple of questions: how many active cells do you end up having? And how many data points?

If I understood correctly, you have 400,000 data points in the dataset, and with the size of your mesh you have 864,000 cells in the mesh. Assuming that your number of active cells is close to that value, you'll need roughly 1.2 TB of ram just to store the sensitivity matrix (using float32 values in the matrix):

```python
n_params = 864_000
n_data = 400_000
required_mem_bytes = n_params * n_data * (32 / 8)
required_mem_gb = required_mem_bytes / 1024**3
```

I suspect that this message you're getting (`Can't expand MemType 0: jcol 798940`) is related to lack of memory to allocate these arrays, but I'm not sure why the error you're getting is not very straight forward.

Could you try to rerun your script after downsampling your data and/or making your mesh more coarse? I want to see if you still get the same error with a smaller system that can fit in your 32GB of memory.

BTW, in the script you shared you have one undefined variable: `sensitivity_weights`. Just mentioning it to take it into account when running it.

**Comment by Alexzqyyds** [comment]
Thank you very much for taking the time to answer my question. Your answer has given me a solution. I am a novice user, it seems that I still need to learn more about your program. I will consult you again if there are any further questions

**Comment by santisoler** [comment]
No worries! I'm glad my reply was helpful. Feel free to add more comments here, or join our [Mattermost channel](https://mattermost.softwareunderground.org/simpeg) if you want to ask more questions.

I'll close this issue since there's no bug with the simpeg code itself. Thanks for taking the time to open it though.
