### ISSUE TITLE
BUG: Error while running Cross-gradient Joint Inversion of Gravity and Magnetic Anomaly Data

### ISSUE THREAD

**Issue by kong-1998** [simpeg/simpeg#1590]
### Describe the issue:

Dear developer:
I encountered a problem while performing joint inversion, and I wanted to export the recovered_model after joint inversion using the mesh-write_model-UBC function, but the error message is as follows:
**ValueError: Number of elements must not change.**
After checking, I found that the reason for recovered_model is that starting'model=np. r_ [background_dens * np. ones (nC), background_stusc * np. ones (nC)] added two sets of data together, but I don't know how to solve this problem.
Can you provide suggestions on how to solve this problem?
Thank you for your help.

### Reproducible code example:

```python
import os
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import tarfile

from discretize import TensorMesh
from discretize.utils import active_from_xyz
from simpeg.utils import plot2Ddata
from simpeg.potential_fields import gravity, magnetics
from simpeg import (
    maps,
    data,
    data_misfit,
    inverse_problem,
    regularization,
    optimization,
    directives,
    inversion,
    utils,
)

np.random.seed(0)

#############################################
# Define File Names
# -----------------
#
# File paths for assets we are loading. To set up the inversion, we require
# topography and field observations. The true model defined on the whole mesh
# is loaded to compare with the inversion result. These files are stored as a
# tar-file on our google cloud bucket:
# "https://storage.googleapis.com/simpeg/doc-assets/gravity.tar.gz"

# # storage bucket where we have the data
data_source = (
    "https://storage.googleapis.com/simpeg/doc-assets/cross_gradient_data.tar.gz"
)

# # download the data
downloaded_data = utils.download(data_source, overwrite=True)

# unzip the tarfile
tar = tarfile.open(downloaded_data, "r")
tar.extractall()
tar.close()

# path to the directory containing our data
dir_path = downloaded_data.split(".")[0] + os.path.sep

# files to work with
topo_filename = dir_path + "test_Topo.xyz"
model_filename = dir_path + "true_model.txt"


#############################################
# Load Data and Plot
# ------------------
#
# Here we load and plot synthetic gravity anomaly data. Topography is generally
# defined as an (N, 3) array. Gravity data is generally defined with 4 columns:
# x, y, z and data.
#

# Load topography
xyz_topo = np.loadtxt(topo_filename)

# Load field data
dobs_grav = np.loadtxt(dir_path + "test_Bouguer.xyz")
dobs_mag = np.loadtxt(dir_path + "test_mag.xyz")

# Define receiver locations and observed data
receiver_locations = dobs_grav[:, 0:3]

dobs_grav = dobs_grav[:, -1]
dobs_mag = dobs_mag[:, -1]

# # Plot
# mpl.rcParams.update({"font.size": 12})

# # gravity data
# fig = plt.figure(figsize=(7, 5))

# ax1 = fig.add_axes([0.1, 0.1, 0.73, 0.85])
# plot2Ddata(receiver_locations, dobs_grav, ax=ax1, contourOpts={"cmap": "bwr"})
# ax1.set_title("Gravity Anomaly")
# ax1.set_xlabel("x (m)")
# ax1.set_ylabel("y (m)")

# ax2 = fig.add_axes([0.8, 0.1, 0.03, 0.85])
# norm = mpl.colors.Normalize(
#     vmin=-np.max(np.abs(dobs_grav)), vmax=np.max(np.abs(dobs_grav))
# )
# cbar = mpl.colorbar.ColorbarBase(
#     ax2, norm=norm, orientation="vertical", cmap=mpl.cm.bwr, format="%.1e"
# )
# cbar.set_label("$mgal$", rotation=270, labelpad=15, size=12)

# # magnetic data
# fig = plt.figure(figsize=(7, 5))
# ax1 = fig.add_axes([0.1, 0.1, 0.73, 0.85])
# plot2Ddata(receiver_locations, dobs_mag, ax=ax1, contourOpts={"cmap": "bwr"})
# ax1.set_title("Magnetic Anomaly")
# ax1.set_xlabel("x (m)")
# ax1.set_ylabel("y (m)")

# ax2 = fig.add_axes([0.8, 0.1, 0.03, 0.85])
# norm = mpl.colors.Normalize(
#     vmin=-np.max(np.abs(dobs_mag)), vmax=np.max(np.abs(dobs_mag))
# )
# cbar = mpl.colorbar.ColorbarBase(
#     ax2, norm=norm, orientation="vertical", cmap=mpl.cm.bwr, format="%.1e"
# )
# cbar.set_label("$nT$", rotation=270, labelpad=15, size=12)

# plt.show()


#############################################
# Assign Uncertainties
# --------------------
#
# Inversion with SimPEG requires that we define standard deviation on our data.
# This represents our estimate of the noise in our data. For gravity inversion,
# a constant floor value is generally applied to all data. For this tutorial,
# the standard deviation on each datum will be 1% of the maximum observed
# gravity anomaly value. For magnetic inversion, the same strategy is performed.
#

maximum_anomaly_grav = np.max(np.abs(dobs_grav))
uncertainties_grav = 0.01 * maximum_anomaly_grav * np.ones(np.shape(dobs_grav))

maximum_anomaly_mag = np.max(np.abs(dobs_mag))
uncertainties_mag = 0.01 * maximum_anomaly_mag * np.ones(np.shape(dobs_mag))


#############################################
# Defining the Survey
# -------------------
#
# Here, we define survey that will be used for this tutorial. Gravity
# surveys are simple to create. The user only needs an (N, 3) array to define
# the xyz locations of the observation locations. From this, the user can
# define the receivers and the source field.
#


# Define the receivers. The data consist of vertical gravity anomaly measurements.
# The set of receivers must be defined as a list.
receiver_grav = gravity.receivers.Point(receiver_locations, components="gz")

# Define the source field and survey for gravity data
source_field_grav = gravity.sources.SourceField(receiver_list=[receiver_grav])
survey_grav = gravity.survey.Survey(source_field_grav)


# Define the component(s) of the field we want to simulate as a list of strings.
# Here we simulation total magnetic intensity data.
components = ["tmi"]

# Use the observation locations and components to define the receivers. To
# simulate data, the receivers must be defined as a list.
receiver_mag = magnetics.receivers.Point(receiver_locations, components=components)

# Define the inducing field H0 = (intensity [nT], inclination [deg], declination [deg])
inclination = 90
declination = 0
strength = 50000

# Define the source field and survey for gravity data
source_field_mag = magnetics.sources.UniformBackgroundField(
    receiver_list=[receiver_mag],
    amplitude=strength,
    inclination=inclination,
    declination=declination,
)
survey_mag = magnetics.survey.Survey(source_field_mag)


#############################################
# Defining the Data
# -----------------
#
# Here is where we define the data that are inverted. The data are defined by
# the survey, the observation values and the standard deviation.
#

data_object_grav = data.Data(
    survey_grav, dobs=dobs_grav, standard_deviation=uncertainties_grav
)
data_object_mag = data.Data(
    survey_mag, dobs=dobs_mag, standard_deviation=uncertainties_mag
)


#############################################
# Defining a Tensor Mesh
# ----------------------
#
# Here, we create the tensor mesh that will be used to invert gravity anomaly
# data. If desired, we could define an OcTree mesh.
#

dh = 1000
hx = [ (dh, 30)]
hy = [ (dh, 30)]
hz = [ (dh, 30)]
mesh = TensorMesh([hx, hy, hz], "CCN")


########################################################
# Starting/Reference Model and Mapping on Tensor Mesh
# ---------------------------------------------------
#
# Here, we create starting and/or reference models for the inversion as
# well as the mapping from the model space to the active cells. Starting and
# reference models can be a constant background value or contain a-priori
# structures. Here, the backgrounds are 1e-6 g/cc and 1e-6 SI for density and
# susceptibility models, respectively. Note that the background values could
# be different for density and susceptibility models.
#

# Define density contrast values for each unit in g/cc.
background_dens, background_susc = 1e-6, 1e-6

# Find the indicies of the active cells in forward model (ones below surface)
ind_active = active_from_xyz(mesh, xyz_topo)

# Define mapping from model to active cells
nC = int(ind_active.sum())
model_map = maps.IdentityMap(nP=nC)  # model consists of a value for each active cell

# Create Wires Map that maps from stacked models to individual model components
# m1 refers to density model, m2 refers to susceptibility
wires = maps.Wires(("density", nC), ("susceptibility", nC))

# Define and plot starting model
starting_model = np.r_[background_dens * np.ones(nC), background_susc * np.ones(nC)]


##############################################
# Define the Physics
# ------------------
#
# Here, we define the physics of the gravity and magnetic problems by using the simulation
# class.
#
# .. tip::
#
#    Since SimPEG v0.21.0 we can use `Choclo
#    <https://www.fatiando.org/choclo>`_ as the engine for running the gravity
#    simulations, which results in faster and more memory efficient runs. Just
#    pass ``engine="choclo"`` when constructing the simulation.
#


simulation_grav = gravity.simulation.Simulation3DIntegral(
    survey=survey_grav,
    mesh=mesh,
    rhoMap=wires.density,
    active_cells=ind_active,
    engine="choclo",
)

simulation_mag = magnetics.simulation.Simulation3DIntegral(
    survey=survey_mag,
    mesh=mesh,
    model_type="scalar",
    chiMap=wires.susceptibility,
    active_cells=ind_active,
)


#######################################################################
# Define the Inverse Problem
# --------------------------
#
# The inverse problem is defined by 4 things:
#
#     1) Data Misfit: a measure of how well our recovered model explains the field data
#     2) Regularization: constraints placed on the recovered model and a priori information
#     3) Coupling: a connection of two different physical property models
#     4) Optimization: the numerical approach used to solve the inverse problem
#

# Define the data misfit. Here the data misfit is the L2 norm of the weighted
# residual between the observed data and the data predicted for a given model.
# Within the data misfit, the residual between predicted and observed data are
# normalized by the data's standard deviation.
dmis_grav = data_misfit.L2DataMisfit(data=data_object_grav, simulation=simulation_grav)
dmis_mag = data_misfit.L2DataMisfit(data=data_object_mag, simulation=simulation_mag)

# Define the regularization (model objective function).
reg_grav = regularization.WeightedLeastSquares(
    mesh, active_cells=ind_active, mapping=wires.density
)
reg_mag = regularization.WeightedLeastSquares(
    mesh, active_cells=ind_active, mapping=wires.susceptibility
)

# Define the coupling term to connect two different physical property models
lamda = 2e12  # weight for coupling term
cross_grad = regularization.CrossGradient(mesh, wires, active_cells=ind_active)

# combo
dmis = dmis_grav + dmis_mag
reg = reg_grav + reg_mag + lamda * cross_grad

# Define how the optimization problem is solved. Here we will use a projected
# Gauss-Newton approach that employs the conjugate gradient solver.
opt = optimization.ProjectedGNCG(
    maxIter=100,
    lower=-5.0,
    upper=5.0,
    maxIterLS=100,
    maxIterCG=100,
    tolCG=1e-3,
    tolX=1e-3,
)

# Here we define the inverse problem that is to be solved
inv_prob = inverse_problem.BaseInvProblem(dmis, reg, opt)


#######################################################################
# Define Inversion Directives
# ---------------------------
#
# Here we define any directiveas that are carried out during the inversion. This
# includes the cooling schedule for the trade-off parameter (beta), stopping
# criteria for the inversion and saving inversion results at each iteration.
#

# Defining a starting value for the trade-off parameter (beta) between the data
# misfit and the regularization.
starting_beta = directives.PairedBetaEstimate_ByEig(beta0_ratio=1e0)
# starting_beta.n_pw_iter = 10

# Defining the fractional decrease in beta and the number of Gauss-Newton solves
# for each beta value.
beta_schedule = directives.PairedBetaSchedule(cooling_factor=5, cooling_rate=1)

# Options for outputting recovered models and predicted data for each beta.
save_iteration = directives.SimilarityMeasureSaveOutputEveryIteration(save_txt=False)

joint_inv_dir = directives.SimilarityMeasureInversionDirective()

stopping = directives.MovingAndMultiTargetStopping(tol=1e-6)

sensitivity_weights = directives.UpdateSensitivityWeights(every_iteration=False)

# Updating the preconditionner if it is model dependent.
update_jacobi = directives.UpdatePreconditioner()


# The directives are defined as a list.
directives_list = [
    joint_inv_dir,
    sensitivity_weights,
    stopping,
    starting_beta,
    beta_schedule,
    save_iteration,
    update_jacobi,
]

#####################################################################
# Running the Inversion
# ---------------------
#
# To define the inversion object, we need to define the inversion problem and
# the set of directives. We can then run the inversion.
#

# Here we combine the inverse problem and the set of directives
inv = inversion.BaseInversion(inv_prob, directives_list)

# Run inversion
recovered_model = inv.run(starting_model)

print("网格单元数量:", mesh.nC)  # 打印网格单元数量
# 假设 recovered_model 是您的模型数据
print("模型数据元素数量:", recovered_model.size)  # 打印模型数据元素数量


mesh.write_UBC("0model_cross.msh")#将3d恢复模型写入一个名为 "recovered_model" 的文件中。
mesh.write_model_UBC("0model_cross.txt", recovered_model)#将恢复模型数据写入一个名为 "recovered_model" 的文件中。
#print(recovered_model, "recovered_model.txt")
```

### Error message:

```shell
ValueError: Number of elements must not change.
```

### Runtime information:

Traceback (most recent call last):
  File "d:\脚本\simpeg\test_cross\cross_gradient.py", line 417, in <module>
    mesh.write_model_UBC("0model_cross.txt", recovered_model)#将恢复模型数据写入一个名为 "recovered_model" 的文件中。
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\Anaconda3\envs\simpeg\Lib\site-packages\discretize\mixins\mesh_io.py", line 270, in write_model_UBC
    modelMat = mesh.reshape(model, "CC", "CC", "M")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\Anaconda3\envs\simpeg\Lib\site-packages\discretize\base\base_regular_mesh.py", line 1000, in reshape
    return switchKernal(x)
           ^^^^^^^^^^^^^^^
  File "D:\software\Anaconda3\envs\simpeg\Lib\site-packages\discretize\base\base_regular_mesh.py", line 937, in switchKernal
    raise ValueError("Number of elements must not change.")
ValueError: Number of elements must not change.

### Context for the issue:

How to export inverted data？

**Comment by thibaut-kobold** [comment]
> Hi @kong-1998. Thanks for opening this issue.
> 
> I think the error you are facing is due to the fact that you are passing the inverted model you get out of the inversion to the `write_model_UBC` function. The `model` argument of this function should be an array with the same size as cells in the mesh: basically an array with the physical properties of each one of the cells in the mesh. In your case, the `recovered_model` is an array that combines the density and susceptibility values only for the active cells in the mesh.
> 
> What I would do is to save the density and the susceptibility models into two different files. In order to get from the `recovered_model` to each one of those you can use the wires mapping. Try this out:
> 
> ```python
> mesh.write_model_UBC("0model_density.txt", wires.density * recovered_model)
> mesh.write_model_UBC("0model_sus.txt", wires.susceptibility * recovered_model)
> ```
> 
> Let me know if that works (I couldn't try it in your script, but I hope it should work).

you also need to include the mapping for the active cells

```python
# Create active map to go from reduce set to full
actvMap = maps.InjectActiveCells(mesh, ind_active, np.nan)
mesh.write_model_UBC("0model_density.txt", actvMap * (wires.density * recovered_model))
mesh.write_model_UBC("0model_sus.txt", actvMap * (wires.susceptibility * recovered_model))
```

**Comment by kong-1998** [comment]
> > Hi @kong-1998. Thanks for opening this issue.
> > I think the error you are facing is due to the fact that you are passing the inverted model you get out of the inversion to the  function. The  argument of this function should be an array with the same size as cells in the mesh: basically an array with the physical properties of each one of the cells in the mesh. In your case, the  is an array that combines the density and susceptibility values only for the active cells in the mesh.`write_model_UBC``model``recovered_model`
> > What I would do is to save the density and the susceptibility models into two different files. In order to get from the  to each one of those you can use the wires mapping. Try this out:`recovered_model`
> > ```python
> > mesh.write_model_UBC("0model_density.txt", wires.density * recovered_model)
> > mesh.write_model_UBC("0model_sus.txt", wires.susceptibility * recovered_model)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if that works (I couldn't try it in your script, but I hope it should work).
> 
> you also need to include the mapping for the active cells
> 
> ```python
> # Create active map to go from reduce set to full
> actvMap = maps.InjectActiveCells(mesh, ind_active, np.nan)
> mesh.write_model_UBC("0model_density.txt", actvMap * (wires.density * recovered_model))
> mesh.write_model_UBC("0model_sus.txt", actvMap * (wires.susceptibility * recovered_model))
> ```

Hello, respected developer. Thank you very much for your help:

The solution you provided has indeed taken effect. Thank you very much for your help and I apologize for any inconvenience caused.
I am a PhD student in geophysics and I am very interested in the Simpeg software. I am amazed by the work of your team.
But I still have some questions to ask you. I found that using Simpeg for joint inversion is mostly concentrated at a depth of about 10km underground. When I tried to use open-source data for deep inversion (70-80km), I found that the signal attenuation phenomenon caused by increasing depth was very obvious. Therefore, I would like to ask you how to overcome this phenomenon. At present, I have an idea to preset a crustal stratification model with different background information such as density, magnetization, seismic wave velocity, etc., but I don't know how to implement it. Can you give me some suggestions?

Thank you again for your help.

Wishing you a wonderful day.
