### ISSUE TITLE
bug in mesh import with numpy >1.9.2

### ISSUE THREAD

**Issue by craigmillernz** [simpeg/simpeg#301]
Hi

I think I found a bug in the UBC mesh import with numpy 1.11.0

On my SFU machine I have numpy 1.11.0. and my script crashes as below.

On my Mira machine I have numpy 1.9.2 and it runs fine. When I downgraded numpy from 1.11.1 to 1.9.2 it ran fine.

Cheers
Craig

############################################

runfile('C:/Users/craigm/Documents/GIT/simpeg/simpegpf/simpegPF/Dev/GRAV/Intgrl_GRAV_Inv_Driver_LdM_Craig.py', wdir='C:/Users/craigm/Documents/GIT/simpeg/simpegpf/simpegPF/Dev/GRAV')
Efficiency Warning: Interpolation will be slow, use setup.py!

        python setup.py build_ext --inplace
Traceback (most recent call last):

File "", line 1, in 
runfile('C:/Users/craigm/Documents/GIT/simpeg/simpegpf/simpegPF/Dev/GRAV/Intgrl_GRAV_Inv_Driver_LdM_Craig.py', wdir='C:/Users/craigm/Documents/GIT/simpeg/simpegpf/simpegPF/Dev/GRAV')

File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
execfile(filename, namespace)

File "C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
exec(compile(scripttext, filename, 'exec'), glob, loc)

File "C:/Users/craigm/Documents/GIT/simpeg/simpegpf/simpegPF/Dev/GRAV/Intgrl_GRAV_Inv_Driver_LdM_Craig.py", line 38, in 
mesh = Mesh.TensorMesh.readUBC(mshfile)

File "C:\Users\craigm\Documents\GIT\simpeg\SimPEG\Mesh\MeshIO.py", line 36, in readUBC
h1 = readCellLine(msh[2])

File "C:\Users\craigm\Documents\GIT\simpeg\SimPEG\Mesh\MeshIO.py", line 24, in readCellLine
re = np.array(sp[0],dtype=int)*(' ' + sp[1])

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('S11') dtype('S11') dtype('S11')

**Comment by craigmillernz** [comment]
OK Dom just told me this was fixed last week, have pulled the new version

**Comment by rowanc1** [comment]
Thanks @fourndo!
