### ISSUE TITLE
AttributeError: module 'discretize' has no attribute 'BaseMesh'

### ISSUE THREAD

**Issue by bernard-giroux** [simpeg/simpeg#777]
I installed SimPEG via pip on a macOS machine running anaconda python 3.7.

I run into this error when I try to run the 1D TDEM inversion example (plot_inversion_1D.py)

```
% pythonw plot_inversion_1D.py 
Traceback (most recent call last):
  File "plot_inversion_1D.py", line 10, in <module>
import SimPEG.EM as EM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/giroux/anaconda3/lib/python3.7/site-packages/SimPEG/EM/__init__.py", line 8, in <module>
    from . import Static
  File "/Users/giroux/anaconda3/lib/python3.7/site-packages/SimPEG/EM/Static/__init__.py", line 1, in <module>
    from . import DC
  File "/Users/giroux/anaconda3/lib/python3.7/site-packages/SimPEG/EM/Static/DC/__init__.py", line 10, in <module>
    from .IODC import IO
  File "/Users/giroux/anaconda3/lib/python3.7/site-packages/SimPEG/EM/Static/DC/IODC.py", line 13, in <module>
    class IO(properties.HasProperties):
  File "/Users/giroux/anaconda3/lib/python3.7/site-packages/SimPEG/EM/Static/DC/IODC.py", line 163, in IO
    "Mesh for discretization", Mesh.BaseMesh, required=True
AttributeError: module 'discretize' has no attribute 'BaseMesh'
```

**Comment by lheagy** [comment]
Hi @bernard-giroux - thanks for pointing this out. We made an update in discretize and are working in #776 to get SimPEG updated. In the mean-time, if you roll-back your version of discretize to 
`discretize == 0.3.11` (e.g. `pip install discretize==0.3.11` then it should resolve this issue.

**Comment by bernard-giroux** [comment]
Hi,  got it working, thanks!
