### ISSUE TITLE
bug in survey.drapeTopo 0.12.0

### ISSUE THREAD

**Issue by craigmillernz** [simpeg/simpeg#804]
In version 0.12.0 I get the following error when apply survey.drapeTopo.  This works in 0.11.6 so appears to have been introduced in the latest.

`dc_survey.drapeTopo(mesh, actind, option="top", topography=topo)`

Traceback (most recent call last):
  File "<ipython-input-12-3115a6134400>", line 1, in <module>
    dc_survey.drapeTopo(mesh, actind, option="top", topography=topo)
  File "D:\Dropbox\GIT\simpeg\SimPEG\EM\Static\DC\SurveyDC.py", line 242, in drapeTopo
    actind=actind, topo=topography
  File "D:\Dropbox\GIT\simpeg\SimPEG\EM\Static\Utils\StaticUtils.py", line 1593, in drapeTopotoLoc
    inds = closestPointsGrid(uniqXYlocs, pts)
  File "D:\Dropbox\GIT\simpeg\SimPEG\EM\Static\Utils\StaticUtils.py", line 1641, in closestPointsGrid
    pt, (grid.shape[0], 1)) - grid)**2.).sum(axis=1).argmin()
ValueError: attempt to get argmin of an empty sequence

**Comment by lheagy** [comment]
@sgkang: would you mind taking a look at this?

**Comment by lheagy** [comment]
Does #843 resolve this? cc @domfournier

**Comment by jcapriot** [comment]
I believe this has likely been addressed, at some point. If you're still getting these issues now though we can address it
