### ISSUE TITLE
Error in install SimPEG on Ubuntu 18.04

### ISSUE THREAD

**Issue by kashkoulimohammad** [simpeg/simpeg#826]
Dear all,

I am trying to install SimPEG on Ubuntu 18.04  but I get these errors:
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-fz74i_y5/discretize-0.4.10/setup.py", line 14, in <module>
    'Intended Audience :: Developers',
Exception: Install requires numpy. If you use conda, `conda install numpy` or you can use pip, `pip install numpy`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    use_2to3=False
  File "/root/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/root/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/root/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/root/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/root/miniconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/root/miniconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/root/miniconda3/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-fz74i_y5/discretize-0.4.10/setup.py", line 14, in <module>
    'Intended Audience :: Developers',
Exception: Install requires numpy. If you use conda, `conda install numpy` or you can use pip, `pip install numpy`

Regards,
Mohammad

**Comment by kashkoulimohammad** [comment]
I installed with pip package and my problems solved.
