### ISSUE TITLE
ImportError: cannot import name 'SolverLU' from 'SimPEG'

### ISSUE THREAD

**Issue by adamkosik** [simpeg/simpeg#888]
With the new version 0.14.0 I obtain this error on initialization of SimPEG.

 I am not using Pardiso and the SolverLU has not been imported in SimPEG yet. I solved it by prepending the import of the `Solvers` to the  import of the `simulation` in `__init__.py`.
```
>>> import SimPEG
Traceback (most recent call last):
  File "D:\Anaconda3\envs\REX_0_14_0\lib\site-packages\SimPEG\simulation.py", line 21, in <module>
    from pymatsolver import Pardiso as DefaultSolver
ImportError: cannot import name 'Pardiso' from 'pymatsolver' (D:\Anaconda3\envs\REX_0_14_0\lib\site-packages\pymatsolver\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\REX_0_14_0\lib\site-packages\SimPEG\__init__.py", line 9, in <module>
    from . import data_misfit
  File "D:\Anaconda3\envs\REX_0_14_0\lib\site-packages\SimPEG\data_misfit.py", line 5, in <module>
    from .simulation import BaseSimulation
  File "D:\Anaconda3\envs\REX_0_14_0\lib\site-packages\SimPEG\simulation.py", line 23, in <module>
    from SimPEG import SolverLU as DefaultSolver
ImportError: cannot import name 'SolverLU' from 'SimPEG' (D:\Anaconda3\envs\REX_0_14_0\lib\site-packages\SimPEG\__init__.py)
```

**Comment by adamkosik** [comment]
The proposed solution is just a workaround. Probably better is to change imports in `simulation.py` to :
```
try:
    from pymatsolver import Pardiso as DefaultSolver
except ImportError:
    from .utils.solver_utils import SolverLU as DefaultSolver
```
instead of
```
try:
    from pymatsolver import Pardiso as DefaultSolver
except ImportError:
    from SimPEG import SolverLU as DefaultSolver
```

**Comment by jcapriot** [comment]
Thanks for catching this, it’s not often that we (the SimPEG developers) are in an environment that cannot import the pardiso solver, and this wasn’t checked.

Do you have details on your installation method? The pardiso solver should work when installing through conda-forge.

**Comment by adamkosik** [comment]
I have used pip 20.0.2, Python 3.7.
